// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitle("FSharp.Data.XRoad.DesignTime")>]
[<assembly: AssemblyProduct("FSharp.Data.XRoad")>]
[<assembly: AssemblyDescription("This library is for the .NET platform implementing FSharp.Data.XRoad.")>]
[<assembly: AssemblyVersion("1.0.0")>]
[<assembly: AssemblyFileVersion("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Data.XRoad.DesignTime"
    let [<Literal>] AssemblyProduct = "FSharp.Data.XRoad"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing FSharp.Data.XRoad."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
