// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Data.XRoad.Runtime")>]
[<assembly: AssemblyProductAttribute("FSharp.Data.XRoad")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing FSharp.Data.XRoad.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Data.XRoad.Runtime"
    let [<Literal>] AssemblyProduct = "FSharp.Data.XRoad"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing FSharp.Data.XRoad."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
