name: General

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.x
      - name: Install tools
        run: dotnet tool restore
      - name: Install dependencies
        run: dotnet paket restore
      - name: Build and test (Release)
        run: dotnet fake build -t All
      - name: Build (Debug)
        run: dotnet build -c Debug -v n

  windows-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.x
      - name: Install tools
        run: dotnet tool restore
      - name: Install dependencies
        run: dotnet paket restore
      - name: Build and test (Release)
        run: dotnet fake build -t All
      - name: Build (Debug)
        run: dotnet build -c Debug -v n
