name: Publish package

on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.412
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.306
      - run: dotnet tool restore
      - name: Install dependencies
        run: dotnet restore
      - name: Run tests
        run: dotnet test --no-restore
        working-directory: ${{ github.workspace }}\tests\FSharp.Data.XRoad.Tests
      - run: dotnet build --configuration Release --no-restore
      - name: Create the package
        run: dotnet paket pack src\FSharp.Data.XRoad --version ${{ github.event.release.tag_name }}
      - name: Push to NuGet
        run: dotnet nuget push src\FSharp.Data.XRoad\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.PUBLISH_TO_NUGET_ORG }} --skip-duplicate
      - name: Push to Github
        run: dotnet nuget push src\FSharp.Data.XRoad\*.nupkg --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ github.token }} --skip-duplicate
